### ISSUE TITLE
The object temperature (T_o) calculation should use the CP for the respective subpage

### ISSUE THREAD

**Issue by oomzay** [melexis-fir/mlx90641-driver-py#1]
Observed: The T_o calculation always uses CP(SP0) cached from RAM[0x0588]

```
//------------------------- To calculation -------------------------------------
irDataCP = frameData[200];
```
[source](https://github.com/melexis-fir/mlx90641-driver-py/blob/8232023ec34e9ca8d240a2b502450e9c63de4a3c/mlx90641/c-code/src/MLX90641_API.c#L599)

Expected: The CP for the actual subpage should be used. I.e.:

- CP(SP0) @ RAM[0x0588] for SP0
- CP(SP1) @ RAM[0x05A8] for SP1

**Comment by mlx-kva** [comment]
Thanks for pointing out to a concerns of yours.
Where did you get the 'expected' from?

**Comment by oomzay** [comment]
It is a bit of an assumption based on the datasheet [1] documenting two CP fields: CP(SP0) and CP(SP1)

If my assumption is not correct can you reveal what the CP(SP1) field is for?

Refs:

1. MLX90641 16x12 IR array Datasheet - REVISION 3 – DECEMBER 9, 2019

**Comment by oomzay** [comment]
One observation that reinforced my assumption is that typically I see similar, plausible values for CP(SP0) and CP(SP1). For example:

- CP(SP0) = 0xfd51
- CP(SP1) = 0xfd3c

**Comment by mlx-kva** [comment]
Hello Oomzay,
Thanks for your close look!
This is a python interface, using the c-code from the MCU library you can find at: https://github.com/melexis/mlx90641-library
I check with those developers, and this is not a mistake. However I acknowledge that the datasheet could be clearer.
Best regards,
Karel.
