### ISSUE TITLE
Kt CP and Kv CP should be decoded as 6 bit fields

### ISSUE THREAD

**Issue by oomzay** [melexis-fir/mlx90641-driver-py#2]
Expected:  Kt CP and Kv CP are decoded as a 6 bit fields [1]:
Observed: Kt CP and Kv CP are decoded as a 5 bit fields [[source](https://github.com/melexis-fir/mlx90641-driver-py/blob/8232023ec34e9ca8d240a2b502450e9c63de4a3c/mlx90641/c-code/src/MLX90641_API.c#L1260)]:

`  cpKta = eeData[49] & 0x001F;
`
`  cpKv = eeData[50] & 0x001F;`

Refs:

1. MLX90641 16x12 IR array Datasheet - REVISION 3 – DECEMBER 9, 2019

**Comment by mlx-kva** [comment]
Hey Oomzay, 
Correct find! Now the good thing is that those numbers are never negative in practice, so currently no errors were induced, however I have updated the driver, just like the pure-c-code lib: https://github.com/melexis/mlx90641-library/commit/3c94aa87384e2cb2afc05b2f2b961ed1c8c87e04
==> now there V1.2.0.
Thanks for pointing this out!
Bye,
Karel.
